Update libraries to versions used by ZAP
Update libraries to match the versions used by ZAP (since 2.4.1, updated
per issue zaproxy/zaproxy#1500). Bouncy Castle libraries are not binary
compatible which leads to issues at runtime.
For example:
 NoClassDefFoundError: org/bouncycastle/x509/extension/
 SubjectKeyIdentifierStructure

Update the following libraries:
 - bcmail-jdk16-146.jar to bcmail-jdk15on-152.jar;
 - bcprov-jdk16-146 to bcprov-jdk15on-152.jar;
 - commons-codec-1.4.jar to commons-codec-1.9.jar.

Add the following library (required by the new code):
 - bcpkix-jdk15on-152.jar.

Update the classes FixedSslCertificateService and ZapSslCertificateUtils
to use latest version of the libraries.
Update Eclipse's classpath to use the newer versions and new library.